### ISSUE TITLE
Option Panel Collapses when background color of 3D view is selected

### ISSUE THREAD

**Issue by aylward** [Kitware/pv-web-viewer#15] opened 2018-02-15 15:41 UTC
See attached image of badness.

Steps to reproduce:
1) Load a volume
2) In the 3D only view, scroll to the bottom of parameter list in lefthand panel
3) At the bottom, the availble background colors subpanel will be only partially scrolled/shown at the bottom
4) Select a new background color, and the entire panel scrunches up to the top.  The only way to get it back is to switch to a different panel (e.g., image load panel) and then switch back.

<img width="365" alt="parameterpanelcollapses" src="https://user-images.githubusercontent.com/279727/36265185-b466ec42-123c-11e8-837a-ae70fb41da0f.PNG">

**Comment by floryst** [comment] 2018-02-16 21:32
A CSS re-write is in order to replace Ant layouts, so hopefully that fixes the collapse instead of changing paraviewweb.

**Comment by floryst** [comment] 2018-03-05 23:22
This should be resolved by #28, but testing was done only on Ubuntu 16.04 Chromium and Firefox. @aylward please try this again to make sure the issue is resolved on your machine.

**Comment by aylward** [comment] 2018-03-07 13:59
This is fixed on Windows 10, Chrome.

**Closed** 2018-03-19 17:26 UTC
